# Generated by Django 3.1.5 on 2023-01-14 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=150)),
                ('image', models.ImageField(default='none', upload_to='')),
                ('is_home_page', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.FloatField(default=0, max_length=300)),
                ('discount_price', models.FloatField(default=0, max_length=300)),
                ('slug', models.SlugField(max_length=150)),
                ('description', models.TextField()),
                ('is_small', models.BooleanField(default=False)),
                ('is_middle', models.BooleanField(default=False)),
                ('is_big', models.BooleanField(default=False)),
                ('is_blog', models.BooleanField(default=False)),
                ('is_pers', models.BooleanField(default=False)),
                ('is_portfolio', models.BooleanField(default=False)),
                ('is_custom', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
            ],
        ),
    ]
