# Generated by Django 3.1.5 on 2023-01-26 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=150)),
                ('short_des', models.CharField(max_length=500)),
                ('icon', models.CharField(max_length=1000)),
                ('is_home_page', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('business_name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=150)),
                ('description', models.TextField()),
                ('short_description', models.TextField(blank=True)),
                ('price', models.FloatField(blank=True, default=0, max_length=300, null=True)),
                ('address', models.CharField(max_length=500)),
                ('cords1', models.CharField(max_length=500)),
                ('cords2', models.CharField(max_length=500)),
                ('image', models.ImageField(default='none', upload_to='other/')),
                ('is_home_page', models.BooleanField(default=False)),
                ('monday', models.CharField(max_length=500)),
                ('tirsdag', models.CharField(max_length=500)),
                ('ondsdag', models.CharField(max_length=500)),
                ('torsdag', models.CharField(max_length=500)),
                ('fredag', models.CharField(max_length=500)),
                ('lørdag', models.CharField(max_length=500)),
                ('søndag', models.CharField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800)),
                ('content', models.TextField(blank=True, max_length=1500)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_conf', models.BooleanField(blank=True, default=False, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product')),
            ],
        ),
    ]
