# Generated by Django 3.1.5 on 2023-01-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='monday',
            new_name='mandag',
        ),
    ]
