# Generated by Django 3.1.5 on 2023-01-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20230127_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='none', upload_to='other/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default='none', upload_to='other/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(default='none', upload_to='other/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=models.ImageField(default='none', upload_to='other/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image6',
            field=models.ImageField(default='none', upload_to='other/'),
        ),
    ]
