# Generated by Django 3.1.5 on 2023-01-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20230120_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stars',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
