# Generated by Django 3.1.5 on 2023-01-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stars',
        ),
    ]
