# Generated by Django 3.1.5 on 2023-01-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='title',
            field=models.CharField(default=True, max_length=800),
            preserve_default=False,
        ),
    ]
