# Generated by Django 3.1.5 on 2023-01-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20230128_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contact_by_phone',
            field=models.FloatField(blank=True, max_length=400, null=True),
        ),
    ]
