# Generated by Django 3.1.5 on 2021-10-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210904_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='included',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
