# Generated by Django 3.1.5 on 2023-01-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productreview_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='is_conf',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
