# Generated by Django 3.1.5 on 2023-01-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productreview_is_conf'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stars',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
