# Generated by Django 3.1.5 on 2021-10-11 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_included'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='included',
        ),
    ]
