# Generated by Django 3.1.5 on 2023-02-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20230207_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='is_conf',
            field=models.BooleanField(default=False),
        ),
    ]
