# Generated by Django 3.1.5 on 2023-02-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20230207_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='category',
            name='short_des',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='product_views', to='store.IpModel'),
        ),
    ]
