# Generated by Django 3.1.5 on 2023-01-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='is_conf',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
