# Generated by Django 3.1.5 on 2022-02-28 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_included'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_blog',
            new_name='is_big',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_business',
            new_name='is_middle',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_ecommerce',
            new_name='is_small',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_personal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_portofolio',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_sale',
        ),
    ]
