# Generated by Django 3.1.5 on 2023-01-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20230125_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='is_conf',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
