# Generated by Django 3.1.5 on 2022-04-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20220228_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_blog',
            field=models.BooleanField(default=False),
        ),
    ]
