# Generated by Django 3.1.5 on 2023-01-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20230117_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_home_page',
            field=models.BooleanField(default=False),
        ),
    ]
