# Generated by Django 3.1.5 on 2022-04-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_is_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_pers',
            field=models.BooleanField(default=False),
        ),
    ]
