# Generated by Django 3.1.5 on 2023-01-25 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20230125_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stars',
        ),
    ]
