# Generated by Django 3.1.5 on 2023-01-17 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_is_home_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='business_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
