# Generated by Django 3.1.5 on 2023-03-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20230217_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seo',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
