# Generated by Django 3.1.5 on 2023-03-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_seo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seo',
            field=models.TextField(blank=True, default='Tjeneste'),
        ),
    ]
