# Generated by Django 3.1.5 on 2023-03-05 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20230305_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seo',
        ),
    ]
