# Generated by Django 3.1.5 on 2023-03-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_product_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seo',
            field=models.TextField(blank=True),
        ),
    ]
