# Generated by Django 3.1.5 on 2023-03-07 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_seo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
    ]
