# Generated by Django 3.1.5 on 2023-01-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parnters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('contact_person', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=400)),
                ('org_nr', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
