# Generated by Django 3.1.5 on 2022-07-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum_post',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forum_post',
            name='slug',
            field=models.SlugField(default=2, max_length=150),
            preserve_default=False,
        ),
    ]
