# Generated by Django 3.1.5 on 2023-01-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parnters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parnters',
            new_name='Partners',
        ),
    ]
