# Generated by Django 3.1.5 on 2022-07-28 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220728_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum_post',
            name='slug',
        ),
    ]
