# Generated by Django 3.1.5 on 2022-07-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_forum_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum_post',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
