# Generated by Django 3.1.5 on 2023-01-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230128_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='contact_person',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='partners',
            name='email',
            field=models.EmailField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='partners',
            name='name',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='partners',
            name='org_nr',
            field=models.CharField(max_length=500),
        ),
    ]
