# Generated by Django 3.1.5 on 2023-01-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_partners_is_payed_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partners',
            old_name='is_payed_member',
            new_name='is_pro',
        ),
    ]
