# Generated by Django 3.1.5 on 2023-02-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230129_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
    ]
