# Generated by Django 3.1.5 on 2023-02-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230207_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='org_nr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
