# Generated by Django 3.1.5 on 2023-02-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230214_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='org_nr',
            field=models.CharField(default=121, max_length=500),
            preserve_default=False,
        ),
    ]
