# Generated by Django 3.1.5 on 2023-02-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230214_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='org_nr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
