# Generated by Django 3.1.5 on 2022-04-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog_Post',
            new_name='Blog',
        ),
    ]
