# Generated by Django 3.1.5 on 2021-09-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210904_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.CharField(choices=[('none', '.......'), ('ecommerce', 'ecommerce'), ('blog', 'Blog'), ('personal', 'Personal'), ('business', 'Business')], default='none', max_length=50),
        ),
        migrations.DeleteModel(
            name='Product_choices',
        ),
    ]
