# Generated by Django 3.1.5 on 2021-09-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210904_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
