# Generated by Django 3.1.5 on 2021-09-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210905_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='hosting',
            field=models.CharField(choices=[('none', '-------'), ('no', 'Nei'), ('yes', 'Ja')], default='none', max_length=50),
        ),
    ]
