# Generated by Django 3.1.5 on 2021-09-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210909_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='hosting',
            field=models.CharField(choices=[('none', '-------'), ('no', 'Nei'), ('yes', 'Ja')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.CharField(choices=[('none', '-------'), ('ecommerce', 'Ecommerce'), ('blog', 'Blog'), ('personal', 'Personal'), ('business', 'Bedrift')], max_length=50),
        ),
    ]
