# Generated by Django 3.1.5 on 2021-09-09 16:42

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20210909_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='order',
            name='hosting',
            field=models.CharField(choices=[('no', 'Nei'), ('yes', 'Ja')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.CharField(choices=[('ecommerce', 'Ecommerce'), ('blog', 'Blog'), ('personal', 'Personal'), ('business', 'Bedrift')], max_length=50),
        ),
    ]
