# Generated by Django 3.1.5 on 2021-09-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20210909_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='num_pages',
            field=models.IntegerField(null=True),
        ),
    ]
