# Generated by Django 3.1.5 on 2021-09-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_num_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.CharField(choices=[('ecommerce', 'Ecommerce'), ('blog', 'Blog'), ('personal', 'Personal'), ('business', 'Bedrift'), ('portofolio', 'Portofolio'), ('custom', 'Custom')], max_length=50),
        ),
    ]
