# Generated by Django 3.1.5 on 2021-09-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20210919_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='color_hex',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
