# Generated by Django 3.1.5 on 2021-09-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_color_hex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='num_pages',
            field=models.FloatField(null=True),
        ),
    ]
