# Generated by Django 3.1.5 on 2021-09-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20210919_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='color_hex',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='num_pages',
            field=models.IntegerField(null=True),
        ),
    ]
