# Generated by Django 3.1.5 on 2021-09-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20210919_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='hosting',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.CharField(max_length=50),
        ),
    ]
