# Generated by Django 3.1.5 on 2021-09-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20210924_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='css',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='hml',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='javascript',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='python_django',
            field=models.CharField(default='', max_length=30),
        ),
    ]
