# Generated by Django 3.1.5 on 2021-09-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20210924_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='num_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
