# Generated by Django 3.1.5 on 2022-02-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_auto_20210924_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='hosting',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='color',
        ),
        migrations.RemoveField(
            model_name='order',
            name='color_hex',
        ),
        migrations.RemoveField(
            model_name='order',
            name='css',
        ),
        migrations.RemoveField(
            model_name='order',
            name='html',
        ),
        migrations.RemoveField(
            model_name='order',
            name='image',
        ),
        migrations.RemoveField(
            model_name='order',
            name='javascript',
        ),
        migrations.RemoveField(
            model_name='order',
            name='num_pages',
        ),
        migrations.RemoveField(
            model_name='order',
            name='page1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='page10',
        ),
        migrations.RemoveField(
            model_name='order',
            name='page2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='page3',
        ),
        migrations.RemoveField(
            model_name='order',
            name='page4',
        ),
        migrations.RemoveField(
            model_name='order',
            name='page5',
        ),
        migrations.RemoveField(
            model_name='order',
            name='page6',
        ),
        migrations.RemoveField(
            model_name='order',
            name='page7',
        ),
        migrations.RemoveField(
            model_name='order',
            name='page8',
        ),
        migrations.RemoveField(
            model_name='order',
            name='page9',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='python_django',
        ),
    ]
