# Generated by Django 3.1.5 on 2022-02-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_order_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='after_14_days',
            field=models.BooleanField(default=False),
        ),
    ]
