# Generated by Django 3.1.5 on 2022-03-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_auto_20220313_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hosting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='short_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
