# Generated by Django 3.1.5 on 2022-03-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_auto_20220315_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='short_name',
            field=models.CharField(default='Nettbutikk', max_length=150),
        ),
    ]
