# Generated by Django 3.1.5 on 2022-03-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_auto_20220315_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tag',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
