# Generated by Django 3.1.5 on 2022-03-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_auto_20220315_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_price',
            field=models.FloatField(default=0, max_length=300),
        ),
    ]
