# Generated by Django 3.1.5 on 2022-03-20 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_order_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status_6',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status_7',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status_8',
        ),
    ]
