# Generated by Django 3.1.5 on 2022-04-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_order_is_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='short_name',
        ),
        migrations.AddField(
            model_name='order',
            name='user_html',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
