# Generated by Django 3.1.5 on 2022-04-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_auto_20220423_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='short_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
