# Generated by Django 3.1.5 on 2022-04-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_order_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_notconfirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_notfinished',
            field=models.BooleanField(default=True),
        ),
    ]
