# Generated by Django 3.1.5 on 2022-04-29 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_auto_20220429_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_notconfirmed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_notfinished',
        ),
    ]
