# Generated by Django 3.1.5 on 2022-07-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_auto_20220429_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tag',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
